gitmedha/sis-frontend

package-lock.json
package.json
src/views/Opportunities/Opportunity.jsx

Targets #442 
Redirection issue after deleting an opportunity from employer page

fixed the issue-> redirection after deleting opportunity issue

---

src/assets/scss/_typography.scss
src/components/content/Utils.jsx
src/views/Institutions/Institution.jsx
src/views/Institutions/InstitutionComponents/InstitutionForm.jsx
src/views/Institutions/InstitutionComponents/MoUs.jsx

1. Fixes MoU display in MoU table
2. Fixes all issues in MoU edit form

MoU bugs fixes

---

src/views/Employers/EmployerComponents/EmploymentConnectionForm.jsx
src/views/Opportunities/OpportunityComponents/EmploymentConnectionForm.jsx
src/views/Students/StudentComponents/EmploymentConnectionForm.jsx

Targets #537 
Now the start date and the end date is looking proper as expected. they are aligned as expected

fixed issue->start date and end date is not aligned

---

src/views/Opportunities/OpportunityComponents/OpportunityForm.jsx

Targets #550 
1. Fixed employer select issue by setting employer id when employer is changed

Fixed employer select issue

---

src/views/Opportunities/OpportunityComponents/OpportunityForm.jsx

Targets #550 
1. Fixed issue in opportunity edit because id was missing - hence picking employer.value for both create and edit opportunity

Employer ID to value

---

src/views/Institutions/Institution.jsx
src/views/Institutions/Institutions.jsx

Targets #432 
1. Sets MoU to empty array if mou.length is zero

Mou bug fixed when there is one MoU

---

src/App.jsx
src/common/commonFunctions.js
src/components/layout/Sidebar.jsx
src/views/Students/Student.jsx
src/views/Students/StudentComponents/EmploymentConnection.jsx
src/views/Students/StudentComponents/EmploymentConnections.jsx
src/views/Students/StudentComponents/ProgramEnrollment.jsx
src/views/Students/StudentComponents/ProgramEnrollments.jsx

Targets #552 
1. Added checks for chapter head user within the application

Chapter Head User role and access

---

src/views/Students/StudentComponents/Details.jsx
src/views/Students/StudentComponents/StudentForm.jsx
src/views/Students/Students.jsx

Targets #552
1. Hide CV upload/delete option
2. Hide CV field from edit form
3. Hide add new student button (and form)

Additional updates done for chapter head access

---

src/common/commonConstants.js
src/graphql/employer.js
src/views/Employers/EmployerComponents/Details.jsx
src/views/Employers/EmployerComponents/EmployerForm.jsx

Targets #562
1. Added fields to employer

Checkboxes fields for employer

---

src/views/Students/StudentComponents/Details.jsx
src/views/Students/StudentComponents/StudentForm.jsx

Targets #547 
Label Changes Medha Champion to Medha Member

Renamed the Medha Champion to Medha Member

---

src/common/commonFunctions.js
src/views/Batches/batchComponents/BatchForm.jsx

Targets #564 
1. Basic role renamed to SRM
2. Added new role "Partnership"
3. Batch grant option restriction

Batch grant option restrictions

---

src/graphql/student.js

Targets #435 
for the employment connections section of student profile page the updated_at field was not showing, I have fixed it.

added updated_at field in student-employer connection query

---

src/components/layout/Search/SearchHits.jsx

feature:-> open a new tab when click on search results

---

src/views/Opportunities/OpportunityComponents/Details.jsx

issue has resolved

---

src/views/Students/StudentComponents/ProgramEnrollments.jsx

issue is fixed

---

src/graphql/batches.js
src/views/Batches/batchActions.js
src/views/Batches/batchComponents/BatchForm.jsx
src/views/Batches/batchComponents/Details.jsx

Targets #581
added new Field in the Batches Mode of payment 
with option 
-Free
-Paid by College
-Paid by Students

New field in Batches module named Mode of Payment

---

src/validations/Batch.js
src/views/Batches/batchComponents/BatchForm.jsx

target #581
Show validation error  under the mode of payment if it is not selected before clicking save button
show error Mode Of Payment is required.

Validation error show in mode of payment

---

src/views/Batches/batchComponents/BatchForm.jsx
src/views/Batches/batchComponents/Details.jsx

renamed studnet fee to contribution

---

src/App.jsx

1. Updated route condition so that it only fails for Chapter Head

route update for partnership

---

src/graphql/student.js
src/views/Students/StudentComponents/AlumniService.jsx
src/views/Students/StudentComponents/AlumniServiceForm.jsx
src/views/Students/StudentComponents/StudentActions.js

Targets #546 
1. These fields should be accessible in the ADD alumni service form.
2. These fields should be accessible in the EDIT alumni service form with saved values pre-selected.
3. These fields should be visible in the Alumni Service Details popup (where we have edit & delete option).

Additional of New Fields in Alumni Engagement module

---

src/views/Students/StudentComponents/AlumniService.jsx
src/views/Students/StudentComponents/AlumniServiceForm.jsx

target #546 
Displaying the SubCategory in the editing form in alumni service.
Feature/546/add new field in alumniservice

Displaying SubCategory in the editing form in alumniservice

---

src/views/Opportunities/Opportunities.jsx

Targets #595
1. Added icon for paid/unpaid GIG opportunity type
2. Added default icon for default status

Added icon for paid/unpaid/default opportunity type

---

src/utils/Form/SelectLookup.jsx

Targets #428
- [X ] Tested locally

issue fixed

---

src/views/Batches/Batches.jsx
src/views/Employers/Employers.jsx
src/views/Institutions/Institutions.jsx
src/views/Students/StudentComponents/ProgramEnrollments.jsx
src/views/Students/Students.jsx

institutes sorting

---

src/validations/Batch.js
src/views/Batches/batchComponents/BatchForm.jsx

disable per student contribution

---

src/assets/scss/main.scss
src/components/content/Avatar.jsx
src/components/content/DetailField.jsx
src/views/Students/StudentComponents/Details.jsx

FIrst letter should be capital

---

src/views/Batches/batchComponents/BatchForm.jsx

fixed issue

---

src/graphql/index.js
src/graphql/operations.js
src/views/Operations/operationsActions.js
src/views/Students/Student.jsx

configured the graphql for operations module

---

src/graphql/operations.js
src/views/Operations/operationsActions.js
src/views/Students/Student.jsx

operations-backend integration->done

---

src/views/Batches/batchComponents/ProgramEnrollment.jsx

target #635 
**Description**
Currently, the bulk certificate generation needs to be fixed, and we would need SRMs to generate and regenerate the certificate for individual students under the program enrollment.
Although, the SRMs should not be able to delete the certificate.

did changes as suggested

---

src/views/Batches/batchComponents/BatchForm.jsx

Targets #639 
1. Uncommented code for batch form submission

Batch form submit issue

---

src/App.jsx

Targets # the my_area and my_state feild is not working properly

my area filter was not working properly

---

src/graphql/student.js
src/validations/Student.js
src/views/Students/StudentComponents/Details.jsx
src/views/Students/StudentComponents/StudentForm.jsx

Targets #619 
1. Family income field in graphql response
2. Family income mandatory numeric field in student form
3. Family annual income in student details

Family income field

---

src/views/Batches/batchComponents/Details.jsx
src/views/Batches/batchComponents/ProgramEnrollment.jsx
src/views/Batches/batchComponents/ProgramEnrollmentForm.jsx
src/views/Institutions/InstitutionComponents/ProgramEnrollment.jsx
src/views/Institutions/InstitutionComponents/ProgramEnrollmentForm.jsx
src/views/Students/StudentComponents/AlumniServiceForm.jsx

renamed all the fee to contribution

---

src/components/content/DetailField.jsx
src/views/Institutions/InstitutionComponents/Contacts.jsx
src/views/Students/Student.jsx
src/views/Students/StudentComponents/Details.jsx
src/views/Students/StudentComponents/ProgramEnrollment.jsx
src/views/Students/StudentComponents/StudentForm.jsx

Targets #{https://medhaofficial.atlassian.net/browse/SIS-11}
- [ X] Tested locally

FIrst letter should be capital 

---

src/components/content/Avatar.jsx

Targets #{https://medhaofficial.atlassian.net/browse/SIS-58}
- [ X] Tested locally

Changed text to bold

---

src/graphql/student.js

Added the fixes for the My area filter on the students listing Page.

Fixed the My Area Filter

---

src/App.jsx
src/assets/scss/main.scss
src/components/layout/Sidebar.jsx
src/graphql/operations.js
src/views/Operations/OperationComponents/OperationCreateform.jsx
src/views/Operations/OperationComponents/OperationDataupdateform.jsx
src/views/Operations/OperationComponents/RowsData.js
src/views/Operations/OperationComponents/operationsActions.js
src/views/Operations/Operations.jsx
src/views/Students/StudentComponents/StudentForm.jsx

Targets #{issueid}
- [ X] Tested locally

Operation new

---

src/components/content/TabPicker.jsx
src/components/content/Table.jsx
src/components/content/Tabs.jsx
src/views/Batches/batchComponents/BatchForm.jsx

console removed

---

src/graphql/student.js
src/views/Students/StudentComponents/ProgramEnrollment.jsx
src/views/Students/StudentComponents/ProgramEnrollmentForm.jsx

Targets https://medhaofficial.atlassian.net/browse/SIS-15?atlOrigin=eyJpIjoiYjIwNjU4YTVjZjBjNDA2Y2FmYTYxN2YwN2QxZWE0YTQiLCJwIjoiaiJ9

changed the course name other as per colored cow change

---

src/views/Students/StudentComponents/EmploymentConnectionForm.jsx

Targets #https://medhaofficial.atlassian.net/jira/software/projects/SIS/boards/1/backlog?selectedIssue=SIS-54
Change lable "Fee" to "Contribution"

Feature/sis 54 

---

src/views/Students/StudentComponents/EmploymentConnectionForm.jsx
src/views/Students/StudentComponents/ProgramEnrollmentForm.jsx

Targets #https://medhaofficial.atlassian.net/browse/SIS-15?focusedCommentId=10076&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-10076

zero showing bug

---

src/views/Employers/EmployerComponents/Address.jsx
src/views/Students/StudentComponents/Address.jsx

Targets #{sis-11}
- [ X] Tested locally

Fix :- Adress field across employer and studnet module

---

src/views/Operations/OperationComponents/OperationDataupdateform.jsx

fixed for assignee

---

src/components/layout/Sidebar.jsx
src/graphql/operations.js

Targets #{OpsModule}
- [x ] Tested locally

Fix :- Graphql Issue

---

src/views/OperationsModule/OperationComponents/AllumuniBulkAdd.jsx
src/views/OperationsModule/OperationComponents/CollegepitchesBulkadd.jsx
src/views/OperationsModule/OperationComponents/Dtesamarth.jsx
src/views/OperationsModule/OperationComponents/OperationCreateform.jsx
src/views/OperationsModule/OperationComponents/OperationDataupdateform.jsx
src/views/OperationsModule/OperationComponents/StudentUpkillingBulkcreate.jsx
src/views/OperationsModule/OperationComponents/UserTot.jsx

Is Active field added

---

src/views/OperationsModule/OperationComponents/Opsdatafeilds.jsx

added fields

---

src/graphql/operations.js
src/views/OperationsModule/OperationComponents/operationsActions.js

Fix :- isActive field to isactive

---

src/assets/scss/main.scss
src/views/OperationsModule/OperationComponents/AllumuniBulkAdd.jsx
src/views/OperationsModule/OperationComponents/AlumunniBulkrow.js
src/views/OperationsModule/OperationComponents/CollegepitchesBulkadd.jsx
src/views/OperationsModule/OperationComponents/DteUpskilingBulk.js
src/views/OperationsModule/OperationComponents/Dtesamarth.jsx
src/views/OperationsModule/OperationComponents/OperationCreateform.jsx
src/views/OperationsModule/OperationComponents/RowsData.js
src/views/OperationsModule/OperationComponents/StudentUpkillingBulkcreate.jsx
src/views/OperationsModule/OperationComponents/StudentupskilingBulk.js
src/views/OperationsModule/OperationComponents/UserTot.jsx
src/views/OperationsModule/OperationComponents/UserTotRowdata.js
src/views/OperationsModule/OperationComponents/collegepitchesBulkrow.js

fix: Cosmetic changes Into the bulk add form

---

src/views/OperationsModule/OperationComponents/AllumuniEdit.jsx
src/views/OperationsModule/OperationComponents/CollegepitchesEdit.jsx
src/views/OperationsModule/OperationComponents/Dtesamarthedit.jsx
src/views/OperationsModule/OperationComponents/TotEdit.jsx
src/views/OperationsModule/OperationComponents/UpskillUpdate.jsx

Ops module date format issue->in all tabs fixed

fixed date issue

---

src/views/OperationsModule/Operations.jsx

Fix :- change project name

---

src/App.jsx
src/components/layout/Sidebar.jsx

changed url

---

src/graphql/student.js
src/graphql/user.js
src/utils/function/lookupOptions.js
src/views/OperationsModule/OperationComponents/UserTotRowdata.js

Feature :- Tariner Field Update

---

src/views/Batches/batchComponents/BatchForm.jsx
src/views/Employers/EmployerComponents/EmployerForm.jsx
src/views/Institutions/InstitutionComponents/InstitutionForm.jsx
src/views/Opportunities/OpportunityComponents/OpportunityForm.jsx
src/views/Students/StudentComponents/StudentForm.jsx

Targets #{issueid}
- [ x] Tested locally

Added Remaining changes

---

src/views/Employers/EmployerComponents/EmployerForm.jsx
src/views/Employers/Employers.jsx
src/views/Institutions/InstitutionComponents/InstitutionForm.jsx
src/views/Institutions/Institutions.jsx

Targets  #https://medhaofficial.atlassian.net/browse/SIS-10

added new validations for employer and institutions

---

src/views/Students/StudentComponents/AlumniServices.jsx

Targets #{https://medhaofficial.atlassian.net/browse/SIS-66}

Fix :-Fee Submission Date to Contribution Submission Date

---

src/views/Students/StudentComponents/ProgramEnrollmentForm.jsx

Targets #https://medhaofficial.atlassian.net/jira/software/projects/SIS/boards/1/backlog?assignee=712020%3Ade66f2c8-5ac5-4526-b4d9-514c6713ffa1&selectedIssue=SIS-33&text=33

disable saving while the batch is duplicate

---

src/assets/scss/main.scss
src/views/OperationsModule/OperationComponents/Alumuniqueriesdata.jsx
src/views/OperationsModule/OperationComponents/CollegePitchdata.jsx
src/views/OperationsModule/OperationComponents/Dtesamarthdatafield.jsx
src/views/OperationsModule/OperationComponents/OperationCreateform.jsx
src/views/OperationsModule/OperationComponents/Opsdatafeilds.jsx
src/views/OperationsModule/OperationComponents/RowsData.js
src/views/OperationsModule/OperationComponents/Totdatafield.jsx
src/views/OperationsModule/OperationComponents/Upskillingdatafield.jsx
src/views/OperationsModule/Operations.jsx

SRM Role added

---

src/views/OperationsModule/OperationComponents/AlumunniBulkrow.js
src/views/OperationsModule/OperationComponents/DteUpskilingBulk.js
src/views/OperationsModule/OperationComponents/StudentupskilingBulk.js
src/views/OperationsModule/OperationComponents/UserTotRowdata.js

Fixing and checking date bold issue

---

src/views/Employers/EmployerComponents/EmployerForm.jsx
src/views/Institutions/InstitutionComponents/InstitutionForm.jsx

Targets #https://medhaofficial.atlassian.net/jira/software/projects/SIS/boards/1/backlog?assignee=712020%3Ade66f2c8-5ac5-4526-b4d9-514c6713ffa1%2C61f92f1baab3620070f54ceb&selectedIssue=SIS-10

renamed the alert message/for employer/institution

---

src/views/Batches/batchComponents/ProgramEnrollmentForm.jsx
src/views/Batches/batchComponents/ProgramEnrollments.jsx
src/views/Students/StudentComponents/ProgramEnrollmentForm.jsx

Targets #https://medhaofficial.atlassian.net/jira/software/projects/SIS/boards/1/backlog?assignee=712020%3Ade66f2c8-5ac5-4526-b4d9-514c6713ffa1%2C61f92f1baab3620070f54ceb&selectedIssue=SIS-33

added duplicate feature for batch module

---

src/store/reducers/Operations/actions.js
src/store/reducers/Operations/index.js
src/store/reducers/Operations/types.js
src/views/OperationsModule/OperationComponents/AlumniSearchBar.jsx
src/views/OperationsModule/OperationComponents/CollegePitchSearch.jsx
src/views/OperationsModule/OperationComponents/SamarthSearchBar.jsx
src/views/OperationsModule/OperationComponents/TotSearchBar.jsx
src/views/OperationsModule/OperationComponents/UpskillSearchBar.jsx
src/views/OperationsModule/Operations.jsx

this resolves the issues of search bar
1. remove previous search values,
2. message for no results

resolved navigation issue and added enable no found alert

---

src/graphql/operations.js
src/views/OperationsModule/OperationComponents/AlumniSearchBar.jsx
src/views/OperationsModule/OperationComponents/CollegePitchSearch.jsx
src/views/OperationsModule/OperationComponents/OpsSearchBar.js
src/views/OperationsModule/OperationComponents/SamarthSearchBar.jsx
src/views/OperationsModule/OperationComponents/TotSearchBar.jsx
src/views/OperationsModule/OperationComponents/UpskillSearchBar.jsx
src/views/OperationsModule/OperationComponents/operationsActions.js
src/views/OperationsModule/Operations.jsx

added dropdowns in search bar

---

src/graphql/batches.js
src/graphql/employer.js
src/graphql/institutes.js
src/graphql/opportunities.js
src/views/Batches/batchComponents/ProgramEnrollment.jsx
src/views/Batches/batchComponents/ProgramEnrollmentForm.jsx
src/views/Employers/EmployerComponents/EmploymentConnection.jsx
src/views/Employers/EmployerComponents/EmploymentConnectionForm.jsx
src/views/Institutions/InstitutionComponents/ProgramEnrollment.jsx
src/views/Institutions/InstitutionComponents/ProgramEnrollmentForm.jsx
src/views/Opportunities/OpportunityComponents/EmploymentConnection.jsx
src/views/Opportunities/OpportunityComponents/EmploymentConnectionForm.jsx

fixed employment connection->program enrollments

---

src/App.jsx
src/components/layout/Sidebar.jsx

Targets #{Ops Routes are closed just regenerated this}

Regenerated Ops Module

---

src/views/Institutions/InstitutionComponents/Details.jsx

added created at field

---

src/components/content/TabPicker.jsx
src/views/OperationsModule/OperationComponents/CollegePitchdata.jsx
src/views/OperationsModule/OperationComponents/CollegepitchesBulkadd.jsx
src/views/OperationsModule/OperationComponents/CollegepitchesEdit.jsx
src/views/OperationsModule/OperationComponents/RowsData.js
src/views/OperationsModule/OperationComponents/StudentupskilingBulk.js
src/views/OperationsModule/OperationComponents/UserTotRowdata.js
src/views/OperationsModule/OperationComponents/collegepitchesBulkrow.js
src/views/OperationsModule/Operations.jsx

Ops Clubing

---

src/views/Batches/Batch.jsx
src/views/Batches/batchActions.js

Targets : https://medhaofficial.atlassian.net/browse/SIS-73
Made an API call named `send-links` and called that API in batch.jsx

Send Link Functionality

---

src/views/Employers/EmployerComponents/EmployerForm.jsx

Bug :employer form edit is not getting save

---

src/graphql/batches.js
src/views/Batches/Batch.jsx

Targets: In this pr, I have corrected the link visibility.

Corrected batch link

---

src/views/Batches/Batch.jsx

Corrected disabled 

---

src/utils/function/OpsModulechecker.js
src/views/OperationsModule/OperationComponents/AllumuniBulkAdd.jsx
src/views/OperationsModule/OperationComponents/AllumuniEdit.jsx
src/views/OperationsModule/OperationComponents/Alumuniqueriesdata.jsx
src/views/OperationsModule/OperationComponents/CollegepitchesBulkadd.jsx
src/views/OperationsModule/OperationComponents/OperationCreateform.jsx
src/views/OperationsModule/OperationComponents/StudentUpkillingBulkcreate.jsx
src/views/OperationsModule/OperationComponents/StudentupskilingBulk.js
src/views/OperationsModule/OperationComponents/Upskillingdatafield.jsx

founder to funder

---

src/views/OperationsModule/OperationComponents/AllumuniBulkAdd.jsx
src/views/OperationsModule/Operations.jsx

added data

---

src/views/OperationsModule/OperationComponents/AllumuniBulkAdd.jsx
src/views/OperationsModule/OperationComponents/AllumuniEdit.jsx
src/views/OperationsModule/OperationComponents/OperationDataupdateform.jsx
src/views/OperationsModule/OperationComponents/Opsdatafeilds.jsx
src/views/OperationsModule/OperationComponents/UserTot.jsx
src/views/OperationsModule/OperationComponents/operationsActions.js
src/views/OperationsModule/Operations.jsx

added some new changes :- spelling issue

---

src/assets/scss/main.scss
src/graphql/operations.js
src/utils/function/OpsModulechecker.js
src/views/Institutions/InstitutionComponents/instituteActions.js
src/views/OperationsModule/OperationComponents/AllumuniBulkAdd.jsx
src/views/OperationsModule/OperationComponents/AllumuniEdit.jsx
src/views/OperationsModule/OperationComponents/AlumniSearchBar.jsx
src/views/OperationsModule/OperationComponents/Alumuniqueriesdata.jsx
src/views/OperationsModule/OperationComponents/AlumunniBulkrow.js
src/views/OperationsModule/OperationComponents/CollegepitchesBulkadd.jsx
src/views/OperationsModule/OperationComponents/CollegepitchesEdit.jsx
src/views/OperationsModule/OperationComponents/Dtesamarth.jsx
src/views/OperationsModule/OperationComponents/OperationCreateform.jsx
src/views/OperationsModule/OperationComponents/OperationDataupdateform.jsx
src/views/OperationsModule/OperationComponents/RowsData.js
src/views/OperationsModule/OperationComponents/StudentUpkillingBulkcreate.jsx
src/views/OperationsModule/OperationComponents/StudentupskilingBulk.js
src/views/OperationsModule/OperationComponents/TotEdit.jsx
src/views/OperationsModule/OperationComponents/UpskillUpdate.jsx
src/views/OperationsModule/OperationComponents/UserTot.jsx
src/views/OperationsModule/OperationComponents/UserTotRowdata.js
src/views/OperationsModule/OperationComponents/collegepitchesBulkrow.js
src/views/OperationsModule/OperationComponents/operationsActions.js
src/views/OperationsModule/Operations.jsx

fix :- start date and date issue fixed

---

src/graphql/batches.js
src/views/Batches/Batch.jsx
src/views/Batches/batchActions.js

Added link functionality

---

src/views/OperationsModule/OperationComponents/Alumuniqueriesdata.jsx
src/views/OperationsModule/OperationComponents/AlumunniBulkrow.js
src/views/OperationsModule/OperationComponents/CollegePitchdata.jsx
src/views/OperationsModule/OperationComponents/CollegepitchesBulkadd.jsx
src/views/OperationsModule/OperationComponents/CollegepitchesEdit.jsx
src/views/OperationsModule/OperationComponents/Deletepopup.jsx
src/views/OperationsModule/OperationComponents/OperationCreateform.jsx
src/views/OperationsModule/OperationComponents/OperationDataupdateform.jsx
src/views/OperationsModule/OperationComponents/Opsdatafeilds.jsx
src/views/OperationsModule/OperationComponents/StudentUpkillingBulkcreate.jsx
src/views/OperationsModule/OperationComponents/UpskillUpdate.jsx
src/views/OperationsModule/OperationComponents/Upskillingdatafield.jsx
src/views/OperationsModule/OperationComponents/UserTot.jsx
src/views/OperationsModule/OperationComponents/operationsActions.js

Delete Entry double check

---

src/graphql/operations.js
src/views/OperationsModule/OperationComponents/OperationCreateform.jsx
src/views/OperationsModule/OperationComponents/OperationDataupdateform.jsx
src/views/OperationsModule/OperationComponents/RowsData.js
src/views/OperationsModule/OperationComponents/StudentUpkillingBulkcreate.jsx
src/views/OperationsModule/OperationComponents/StudentupskilingBulk.js
src/views/OperationsModule/OperationComponents/UpskillUpdate.jsx
src/views/OperationsModule/OperationComponents/Upskillingdatafield.jsx

Program name update

---

src/views/OperationsModule/OperationComponents/AllumuniBulkAdd.jsx
src/views/OperationsModule/OperationComponents/CollegepitchesBulkadd.jsx
src/views/OperationsModule/OperationComponents/OperationCreateform.jsx
src/views/OperationsModule/OperationComponents/StudentUpkillingBulkcreate.jsx
src/views/OperationsModule/OperationComponents/UserTot.jsx

Added all the popup

---

src/graphql/operations.js
src/utils/function/OpsModulechecker.js
src/views/OperationsModule/OperationComponents/AllumuniBulkAdd.jsx
src/views/OperationsModule/OperationComponents/Alumuniqueriesdata.jsx
src/views/OperationsModule/OperationComponents/CollegePitchdata.jsx
src/views/OperationsModule/OperationComponents/CollegepitchesBulkadd.jsx
src/views/OperationsModule/OperationComponents/OperationCreateform.jsx
src/views/OperationsModule/OperationComponents/OperationDataupdateform.jsx
src/views/OperationsModule/OperationComponents/Opsdatafeilds.jsx
src/views/OperationsModule/OperationComponents/StudentUpkillingBulkcreate.jsx
src/views/OperationsModule/OperationComponents/Totdatafield.jsx
src/views/OperationsModule/OperationComponents/Upskillingdatafield.jsx
src/views/OperationsModule/OperationComponents/UserTot.jsx

Alumni bulk add

---

src/graphql/operations.js
src/views/OperationsModule/OperationComponents/AlumniSearchBar.jsx
src/views/OperationsModule/OperationComponents/Opsdatafeilds.jsx
src/views/OperationsModule/OperationComponents/Totdatafield.jsx
src/views/OperationsModule/OperationComponents/UpskillSearchBar.jsx
src/views/OperationsModule/OperationComponents/UpskillUpdate.jsx
src/views/OperationsModule/OperationComponents/Upskillingdatafield.jsx

Feature :- added start date and end date in student upskilling module

---

src/graphql/operations.js
src/views/OperationsModule/OperationComponents/UpskillSearchBar.jsx

fix: start date end date value not reflecting

---

src/views/Employers/EmployerComponents/EmployerForm.jsx

Fix :- contact info is fetching null value

---

src/views/OperationsModule/OperationComponents/AlumniSearchBar.jsx
src/views/OperationsModule/OperationComponents/TotSearchBar.jsx
src/views/OperationsModule/OperationComponents/UpskillSearchBar.jsx

Alphabatical order in search bar

---

src/utils/function/OpsModulechecker.js
src/views/OperationsModule/OperationComponents/AllumuniBulkAdd.jsx
src/views/OperationsModule/OperationComponents/AlumunniBulkrow.js

Added alumuni data

---

src/views/Students/StudentComponents/ProgramEnrollmentForm.jsx

programme enrollment form edit

---

src/views/OperationsModule/OperationComponents/AlumunniBulkrow.js

added check

---

src/views/OperationsModule/OperationComponents/CollegepitchesBulkadd.jsx
src/views/OperationsModule/OperationComponents/StudentUpkillingBulkcreate.jsx
src/views/OperationsModule/OperationComponents/StudentupskilingBulk.js
src/views/OperationsModule/OperationComponents/UpskillUpdate.jsx

Added required changes on student upskilling

---

src/views/OperationsModule/OperationComponents/UserTotRowdata.js

district added

---

src/utils/function/lookupOptions.js
src/views/Students/StudentComponents/ProgramEnrollment.jsx

Add fixes for issue while user clicking on `Generate Certificate`

---

src/graphql/operations.js
src/views/OperationsModule/OperationComponents/AllumuniBulkAdd.jsx
src/views/OperationsModule/OperationComponents/CollegePitchdata.jsx
src/views/OperationsModule/OperationComponents/CollegepitchesBulkadd.jsx
src/views/OperationsModule/OperationComponents/CollegepitchesEdit.jsx
src/views/OperationsModule/OperationComponents/Deletepopup.jsx
src/views/OperationsModule/OperationComponents/OperationCreateform.jsx
src/views/OperationsModule/OperationComponents/StudentUpkillingBulkcreate.jsx
src/views/OperationsModule/OperationComponents/UserTot.jsx
src/views/OperationsModule/OperationComponents/collegepitchesBulkrow.js

Targets #{Program enrolment feature}

Pitching pragrame enrollment feature added

---

src/views/OperationsModule/OperationComponents/CollegepitchesBulkadd.jsx
src/views/OperationsModule/OperationComponents/CollegepitchesEdit.jsx

Spelling correct

---

src/views/OperationsModule/OperationComponents/CollegePitchSearch.jsx
src/views/OperationsModule/OperationComponents/OpsSearchBar.js
src/views/OperationsModule/OperationComponents/UpskillSearchBar.jsx

Targets #https://medhaofficial.atlassian.net/browse/SIS-103

linked to program table

---

src/views/OperationsModule/OperationComponents/AllumuniBulkAdd.jsx
src/views/OperationsModule/OperationComponents/AlumunniBulkrow.js
src/views/OperationsModule/OperationComponents/CollegepitchesBulkadd.jsx
src/views/OperationsModule/OperationComponents/OperationCreateform.jsx
src/views/OperationsModule/OperationComponents/OperationDataupdateform.jsx
src/views/OperationsModule/OperationComponents/RowsData.js
src/views/OperationsModule/OperationComponents/StudentUpkillingBulkcreate.jsx
src/views/OperationsModule/OperationComponents/StudentupskilingBulk.js
src/views/OperationsModule/OperationComponents/UserTot.jsx
src/views/OperationsModule/OperationComponents/collegepitchesBulkrow.js
src/views/OperationsModule/Operations.jsx

Institutions filter issue

---

src/views/OperationsModule/OperationComponents/CollegepitchesBulkadd.jsx

srm mandat

---

src/views/OperationsModule/Operations.jsx

added srm_name

---

src/views/OperationsModule/OperationComponents/AllumuniBulkAdd.jsx
src/views/OperationsModule/OperationComponents/AlumunniBulkrow.js
src/views/OperationsModule/OperationComponents/CollegepitchesBulkadd.jsx
src/views/OperationsModule/OperationComponents/OperationCreateform.jsx
src/views/OperationsModule/OperationComponents/RowsData.js
src/views/OperationsModule/OperationComponents/StudentUpkillingBulkcreate.jsx
src/views/OperationsModule/OperationComponents/StudentupskilingBulk.js
src/views/OperationsModule/OperationComponents/UserTot.jsx

Ops data buld add

---

src/views/OperationsModule/OperationComponents/AllumuniEdit.jsx
src/views/OperationsModule/OperationComponents/AlumniSearchBar.jsx
src/views/OperationsModule/OperationComponents/Alumuniqueriesdata.jsx
src/views/OperationsModule/OperationComponents/CollegePitchSearch.jsx
src/views/OperationsModule/OperationComponents/CollegePitchdata.jsx
src/views/OperationsModule/OperationComponents/CollegepitchesEdit.jsx
src/views/OperationsModule/OperationComponents/OperationDataupdateform.jsx
src/views/OperationsModule/OperationComponents/OpsSearchBar.js
src/views/OperationsModule/OperationComponents/Opsdatafeilds.jsx
src/views/OperationsModule/OperationComponents/TotEdit.jsx
src/views/OperationsModule/OperationComponents/TotSearchBar.jsx
src/views/OperationsModule/OperationComponents/Totdatafield.jsx
src/views/OperationsModule/OperationComponents/UpskillSearchBar.jsx
src/views/OperationsModule/OperationComponents/UpskillUpdate.jsx
src/views/OperationsModule/OperationComponents/Upskillingdatafield.jsx
src/views/OperationsModule/Operations.jsx

Targets #https://medhaofficial.atlassian.net/jira/software/projects/SIS/boards/1/backlog?assignee=712020%3Ade66f2c8-5ac5-4526-b4d9-514c6713ffa1&selectedIssue=SIS-106

Feature/sis 106-> search feature-> ops module bug fixes

---

src/views/OperationsModule/OperationComponents/TotSearchBar.jsx

Targets #https://medhaofficial.atlassian.net/jira/software/projects/SIS/boards/1/backlog?assignee=712020%3Ade66f2c8-5ac5-4526-b4d9-514c6713ffa1&selectedIssue=SIS-106

system adoption fix

---

src/views/OperationsModule/OperationComponents/OperationCreateform.jsx
src/views/OperationsModule/OperationComponents/RowsData.js

filter batch option

---

src/views/OperationsModule/OperationComponents/AllumuniBulkAdd.jsx
src/views/OperationsModule/OperationComponents/CollegepitchesBulkadd.jsx
src/views/OperationsModule/OperationComponents/OperationCreateform.jsx
src/views/OperationsModule/OperationComponents/StudentUpkillingBulkcreate.jsx
src/views/OperationsModule/OperationComponents/StudentupskilingBulk.js
src/views/OperationsModule/OperationComponents/UserTot.jsx

Operation bulk add issue :- the rows shows empty after saving the data

---

src/graphql/operations.js
src/views/OperationsModule/OperationComponents/AllumuniBulkAdd.jsx
src/views/OperationsModule/OperationComponents/CollegepitchesBulkadd.jsx
src/views/OperationsModule/OperationComponents/OperationCreateform.jsx
src/views/OperationsModule/OperationComponents/RowsData.js
src/views/OperationsModule/OperationComponents/StudentUpkillingBulkcreate.jsx
src/views/OperationsModule/OperationComponents/StudentupskilingBulk.js
src/views/OperationsModule/OperationComponents/UserTot.jsx
src/views/OperationsModule/Operations.jsx

resolved batch option problem

---

src/views/OperationsModule/OperationComponents/OpsSearchBar.js
src/views/OperationsModule/OperationComponents/UpskillSearchBar.jsx

Targets #https://medhaofficial.atlassian.net/jira/software/projects/SIS/boards/1/backlog?assignee=712020%3Ade66f2c8-5ac5-4526-b4d9-514c6713ffa1%2C712020%3A648b44e9-a9e6-45e0-8f74-2143f195a303&selectedIssue=SIS-128

added start end date & category->ops search feature

---

src/views/OperationsModule/OperationComponents/RowsData.js
src/views/OperationsModule/Operations.jsx

operation moduke changes

---

src/views/Batches/Batches.jsx

username issue

---

src/views/OperationsModule/OperationComponents/UploadFile.jsx
src/views/Students/StudentComponents/ModalShowmassedit.jsx

close button

---

src/views/Students/StudentComponents/EmploymentConnectionForm.jsx

Added status change update

---

src/views/Students/StudentComponents/EmploymentConnection.jsx

Added end condition for appranteship started status

---

src/views/Students/StudentComponents/EmploymentConnection.jsx

File changes

---

src/views/Students/StudentComponents/EmploymentConnectionForm.jsx

Employment connection Changes

---

src/views/Students/StudentComponents/EmploymentConnection.jsx

End date issue

---

src/views/Opportunities/OpportunityComponents/OpportunityForm.jsx

Compensation type is changed

---

src/views/OperationsModule/OperationComponents/UploadFile.jsx
src/views/OperationsModule/Operations.jsx

Upload opssdata

---

src/graphql/opportunities.js
src/utils/function/lookupOptions.js
src/views/Students/MassEdit/AlumMassEdit.jsx
src/views/Students/MassEdit/BulkMassEdit.jsx
src/views/Students/MassEdit/BulkMassEmployerEdit.jsx
src/views/Students/MassEdit/EmploymentmassEdit.jsx
src/views/Students/StudentComponents/CheckBoxForm.jsx
src/views/Students/StudentComponents/MassEdit.jsx
src/views/Students/StudentComponents/MassEmployerUpload.jsx
src/views/Students/StudentComponents/ModalShowmassedit.jsx

Mass alumni edit

---

src/views/Calendar/Calendar.jsx
src/views/Calendar/calendarComponents/EventForm.jsx
src/views/Calendar/calendarComponents/ViewEvent.js
src/views/Calendar/calendarComponents/calendarActions.js

Targets #https://medhaofficial.atlassian.net/jira/software/projects/SIS/boards/1/backlog?assignee=712020%3Ad4b8582a-1d59-4cea-a36c-758e04998bc8&selectedIssue=SIS-123

added alert and other require checklist changes

---

src/views/Calendar/Calendar.jsx
src/views/Calendar/calendarComponents/EventForm.jsx

resolved create event modal hide issue

---

src/validations/Employer.js
src/validations/Opportunity.js
src/validations/Student.js

validation in opportunity module

---

src/graphql/operations.js
src/views/OperationsModule/OperationComponents/OperationCreateform.jsx
src/views/OperationsModule/OperationComponents/Opsdatafeilds.jsx
src/views/OperationsModule/OperationComponents/RowsData.js

addded some changes for hiding batch data  for ops module

---

src/views/Calendar/Calendar.jsx
src/views/Calendar/calendarComponents/EventForm.jsx
src/views/Calendar/calendarComponents/ViewEvent.js
src/views/Calendar/calendarComponents/calendarActions.js

Targets #https://medhaofficial.atlassian.net/browse/SIS-123

Calendar Module-> Modifications 

---

src/views/OperationsModule/OperationComponents/OperationCreateform.jsx
src/views/OperationsModule/OperationComponents/RowsData.js

Added Student Type

---

src/views/Calendar/calendarComponents/EventForm.jsx
src/views/Students/Student.jsx
src/views/Students/StudentComponents/AlumniService.jsx
src/views/Students/StudentComponents/AlumniServiceForm.jsx
src/views/Students/StudentComponents/AlumniServices.jsx

changed label alumni service to alumni engagement

---

src/views/Employers/EmployerComponents/EmployerForm.jsx
src/views/Employers/EmployerComponents/OpportunityForm.jsx
src/views/Institutions/InstitutionComponents/InstitutionForm.jsx
src/views/Opportunities/OpportunityComponents/OpportunityForm.jsx
src/views/Students/StudentComponents/StudentForm.jsx

Reordered Address Field

---

src/views/OperationsModule/OperationComponents/OperationCreateform.jsx

batch changes

---

src/views/OperationsModule/OperationComponents/OperationCreateform.jsx

Hide batch name in the ops module

---

src/views/OperationsModule/OperationComponents/OperationCreateform.jsx
src/views/OperationsModule/OperationComponents/RowsData.js

Aligment change in program name field

---

src/views/OperationsModule/OperationComponents/StudentupskilingBulk.js
src/views/OperationsModule/Operations.jsx

Student upskilling changes

---

src/views/Employers/EmployerComponents/EmployerForm.jsx
src/views/Employers/EmployerComponents/EmploymentConnectionForm.jsx
src/views/Employers/EmployerComponents/OpportunityForm.jsx
src/views/Institutions/InstitutionComponents/InstitutionForm.jsx
src/views/OperationsModule/OperationComponents/OperationCreateform.jsx
src/views/OperationsModule/OperationComponents/OperationDataupdateform.jsx
src/views/OperationsModule/OperationComponents/Opsdatafeilds.jsx
src/views/OperationsModule/OperationComponents/RowsData.js
src/views/OperationsModule/OperationComponents/StudentUpkillingBulkcreate.jsx
src/views/OperationsModule/OperationComponents/StudentupskilingBulk.js
src/views/OperationsModule/OperationComponents/UpskillUpdate.jsx
src/views/Opportunities/OpportunityComponents/EmploymentConnectionForm.jsx
src/views/Opportunities/OpportunityComponents/OpportunityForm.jsx
src/views/Students/Student.jsx
src/views/Students/StudentComponents/AlumniService.jsx
src/views/Students/StudentComponents/AlumniServiceForm.jsx
src/views/Students/StudentComponents/AlumniServices.jsx
src/views/Students/StudentComponents/StudentForm.jsx

ticket number 121,142,140,133,117 are being deployed

---

src/validations/Calendar.js
src/views/Calendar/calendarComponents/EventForm.jsx

Targets #https://medhaofficial.atlassian.net/jira/software/projects/SIS/boards/1/backlog?assignee=712020%3Ade66f2c8-5ac5-4526-b4d9-514c6713ffa1%2C712020%3Ad4b8582a-1d59-4cea-a36c-758e04998bc8&selectedIssue=SIS-123

fixed calendar bugs

---

src/views/Batches/Batches.jsx
src/views/Employers/Employers.jsx
src/views/Institutions/Institutions.jsx
src/views/Opportunities/Opportunities.jsx
src/views/Students/Students.jsx

Search feature/bugs

---

src/views/Batches/Batches.jsx
src/views/Batches/batchComponents/BatchSearchBar.jsx
src/views/Employers/EmployerComponents/EmployerSearchBar.jsx
src/views/Employers/Employers.jsx
src/views/Institutions/InstitutionComponents/InstitutionSearchBar.jsx
src/views/Institutions/Institutions.jsx

made changes in rest modules

---

src/validations/Batch.js
src/validations/Employer.js
src/validations/Opportunity.js
src/validations/Student.js
src/views/OperationsModule/OperationComponents/OpsSearchBar.js
src/views/OperationsModule/OperationComponents/UpskillSearchBar.jsx
src/views/OperationsModule/Operations.jsx

Sis-125,128,136 are deploying on 9th may

---

src/graphql/student.js
src/views/Students/StudentComponents/Details.jsx
src/views/Students/StudentComponents/StudentForm.jsx

Added dropdown in student component as your plan after current course

---

src/graphql/student.js
src/views/Students/StudentComponents/AlumniService.jsx
src/views/Students/StudentComponents/AlumniServiceForm.jsx

feature enhacement  sis-144

---

src/views/Students/StudentComponents/AlumniServiceForm.jsx

Alumni service captilaze issue

---

src/views/Students/StudentComponents/AlumniServiceForm.jsx

status feild sligment

---

src/validations/Student.js
src/views/Students/StudentComponents/ProgramEnrollmentForm.jsx

Targets #https://medhaofficial.atlassian.net/browse/SIS-147?focusedCommentId=10646&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-10646

Submit is not working-> program Enrollements form

---

src/views/OperationsModule/OperationComponents/CheckValuesOpsUploadedData.jsx
src/views/OperationsModule/OperationComponents/UploadFile.jsx
src/views/OperationsModule/Operations.jsx

Added changes

---

src/views/Employers/EmployerComponents/EmployerForm.jsx
src/views/Institutions/InstitutionComponents/InstitutionForm.jsx
src/views/Opportunities/OpportunityComponents/OpportunityForm.jsx
src/views/Students/StudentComponents/StudentForm.jsx

district aligment changes

---

src/components/layout/Sidebar.jsx
src/views/OperationsModule/OperationComponents/OperationCreateform.jsx
src/views/OperationsModule/OperationComponents/Opsdatafeilds.jsx
src/views/OperationsModule/OperationComponents/RowsData.js
src/views/OperationsModule/Operations.jsx

src file added

---

src/graphql/student.js
src/views/Batches/batchComponents/ProgramEnrollmentForm.jsx
src/views/Institutions/InstitutionComponents/ProgramEnrollmentForm.jsx
src/views/Students/StudentComponents/ProgramEnrollmentForm.jsx
src/views/Students/StudentComponents/StudentActions.js

Course name changes

---

src/views/Students/StudentComponents/AlumniServiceForm.jsx

Targets #https://medhaofficial.atlassian.net/jira/software/projects/SIS/boards/1/backlog?assignee=712020%3Ade66f2c8-5ac5-4526-b4d9-514c6713ffa1&selectedIssue=SIS-144

Selecting Paid field require fields are not required -> Fixed

---

src/views/Students/MassEdit/AlumMassEdit.jsx
src/views/Students/MassEdit/EmploymentmassEdit.jsx
src/views/Students/StudentComponents/MassEdit.jsx
src/views/Students/StudentComponents/MassEmployerUpload.jsx

Mass edit1

---

src/assets/scss/media/sm.scss
src/views/Batches/batchComponents/BatchForm.jsx
src/views/Batches/batchComponents/BatchSessionForm.jsx
src/views/Batches/batchComponents/ProgramEnrollmentForm.jsx
src/views/Employers/EmployerComponents/EmployerForm.jsx
src/views/Employers/EmployerComponents/EmploymentConnectionForm.jsx
src/views/Employers/EmployerComponents/OpportunityForm.jsx
src/views/Institutions/InstitutionComponents/InstitutionForm.jsx
src/views/Institutions/InstitutionComponents/ProgramEnrollmentForm.jsx
src/views/OperationsModule/OperationComponents/OperationDataupdateform.jsx
src/views/Opportunities/OpportunityComponents/EmploymentConnectionForm.jsx
src/views/Students/StudentComponents/AlumniServiceForm.jsx
src/views/Students/StudentComponents/EmploymentConnectionForm.jsx
src/views/Students/StudentComponents/ProgramEnrollmentForm.jsx
src/views/Students/StudentComponents/StudentForm.jsx
src/views/Students/StudentComponents/StudentsSearchBar.jsx
src/views/Students/Students.jsx

Targets #https://medhaofficial.atlassian.net/jira/software/projects/SIS/boards/1/backlog?assignee=712020%3Ade66f2c8-5ac5-4526-b4d9-514c6713ffa1&selectedIssue=SIS-143

resolve spacing issues in all forms and students module

---

src/assets/scss/_tab-picker.scss
src/assets/scss/main.scss
src/assets/scss/media/sm.scss
src/components/content/Pagination.jsx
src/components/content/TabPicker.jsx
src/components/content/Table.jsx
src/views/Batches/batchComponents/BatchSearchBar.jsx
src/views/Employers/EmployerComponents/EmployerSearchBar.jsx
src/views/Institutions/InstitutionComponents/InstitutionSearchBar.jsx
src/views/Institutions/Institutions.jsx
src/views/OperationsModule/OperationComponents/AlumniSearchBar.jsx
src/views/OperationsModule/OperationComponents/OpsSearchBar.js
src/views/OperationsModule/OperationComponents/TotSearchBar.jsx
src/views/OperationsModule/OperationComponents/UpskillSearchBar.jsx
src/views/OperationsModule/Operations.jsx
src/views/Opportunities/OpportunityComponents/OpportunitySearchBar.jsx
src/views/Students/MassEdit/AlumMassEdit.jsx
src/views/Students/MassEdit/EmploymentmassEdit.jsx
src/views/Students/StudentComponents/MassEdit.jsx
src/views/Students/StudentComponents/MassEmployerUpload.jsx
src/views/Students/StudentComponents/StudentsSearchBar.jsx
src/views/Students/Students.jsx

Responsive tabs and searchBar changes

---

src/assets/scss/main.scss
src/views/OperationsModule/Operations.jsx

removed bottom space inside the button

---

src/assets/scss/media/sm.scss
src/components/content/Table.jsx

resolved pagination gap

---

package-lock.json
src/components/layout/Sidebar.jsx
src/validations/Student.js
src/views/Batches/batchComponents/ProgramEnrollments.jsx
src/views/Batches/sessions/updateSession.jsx
src/views/Dashboard/components/ProgramEnrollments.jsx
src/views/Employers/EmployerComponents/Opportunities.jsx
src/views/Institutions/InstitutionComponents/ProgramEnrollments.jsx
src/views/OperationsModule/Operation.jsx
src/views/OperationsModule/OperationComponents/AllumuniBulkAdd.jsx
src/views/OperationsModule/OperationComponents/Deletepopup.jsx
src/views/OperationsModule/OperationComponents/OperationCreateform.jsx
src/views/OperationsModule/OperationComponents/OperationDataupdateform.jsx
src/views/OperationsModule/OperationComponents/StudentUpkillingBulkcreate.jsx
src/views/OperationsModule/OperationComponents/UpskillUpdate.jsx
src/views/OperationsModule/OperationComponents/Upskillingdatafield.jsx
src/views/OperationsModule/OperationComponents/operationsActions.js
src/views/Opportunities/Opportunities.jsx
src/views/Students/MassEdit/AlumMassEdit.jsx
src/views/Students/MassEdit/BulkMassEmployerEdit.jsx
src/views/Students/MassEdit/EmploymentmassEdit.jsx
src/views/Students/Student.jsx
src/views/Students/StudentComponents/AlumniServiceForm.jsx
src/views/Students/StudentComponents/EmploymentConnectionForm.jsx
src/views/Students/StudentComponents/EmploymentConnections.jsx
src/views/Students/StudentComponents/ProgramEnrollmentForm.jsx
src/views/Students/StudentComponents/ProgramEnrollments.jsx

Targets #https://medhaofficial.atlassian.net/jira/software/projects/SIS/boards/1/backlog?selectedIssue=SIS-132&text=Replac

replacement of meilisearch in the whole module

---

src/views/OperationsModule/Operations.jsx
src/views/Students/Students.jsx

hide mass edit and upload

---

jsconfig.json
package-lock.json
src/views/Calendar/Calendar.jsx
src/views/Calendar/calendarComponents/EventForm.jsx
src/views/Calendar/calendarComponents/calendarActions.js
src/views/Employers/EmployerComponents/EmploymentConnectionForm.jsx
src/views/Opportunities/OpportunityComponents/EmploymentConnectionForm.jsx
src/views/Students/MassEdit/EmploymentmassEdit.jsx
src/views/Students/StudentComponents/EmploymentConnectionForm.jsx
src/views/Students/StudentComponents/ModalShowmassedit.jsx
src/views/Students/StudentComponents/StudentForm.jsx

Targets #{ Calendar date range issue}

fixed calender issue

---

src/views/Calendar/calendarComponents/ViewEvent.js

Targets #{calendar ( Delete event button label changes ) }

button label changes

---

jsconfig.json
src/views/Calendar/calendarComponents/calendarActions.js

Targets #{added shortcut to import file}

import shortcut

---

src/views/Students/StudentComponents/Details.jsx
src/views/Students/StudentComponents/StudentForm.jsx

hided the current course in student form

---

src/views/Students/StudentComponents/Details.jsx

hide current course in the details>students

---

src/App.jsx
src/common/commonFunctions.js
src/components/layout/Sidebar.jsx
src/validations/Student.js
src/views/Students/StudentComponents/AlumniServiceForm.jsx
src/views/Students/StudentComponents/ProgramEnrollmentForm.jsx
src/views/Students/StudentComponents/StudentForm.jsx

Student form is not working made appropriate changes

---

src/validations/Student.js

removed validation

---

jsconfig.json
src/views/Students/MassEdit/AlumMassEdit.jsx
src/views/Students/MassEdit/EmploymentmassEdit.jsx
src/views/Students/StudentComponents/MassEdit.jsx
src/views/Students/StudentComponents/MassEmployerUpload.jsx

Massedit renew

---

src/views/Students/StudentComponents/MassEmployerUpload.jsx
src/views/Students/Students.jsx

removed console

---

src/validations/Calendar.js
src/views/Calendar/Calendar.jsx
src/views/Calendar/calendarComponents/EventForm.jsx
src/views/Calendar/calendarComponents/ViewEvent.js

added new Calendar changes

---

src/views/Students/StudentComponents/ProgramEnrollmentForm.jsx

Added src file

---

src/views/Students/StudentComponents/ProgramEnrollmentForm.jsx

Course file changes

---

src/views/OperationsModule/Operations.jsx
src/views/Students/StudentComponents/Details.jsx
src/views/Students/StudentComponents/StudentForm.jsx
src/views/Students/Students.jsx

unhide stg changes

---

src/assets/scss/main.scss
src/validations/Student.js
src/views/Batches/Batches.jsx
src/views/Employers/Employers.jsx
src/views/Students/StudentComponents/StudentForm.jsx

release fixes for staging testing

---

src/views/Batches/batchActions.js
src/views/Calendar/Calendar.jsx

fixed the calendar crashing on month week days

---

src/utils/function/lookupOptions.js
src/views/Batches/batchComponents/ProgramEnrollmentForm.jsx
src/views/Students/StudentComponents/ProgramEnrollmentForm.jsx

fixed new testing issues

---

src/graphql/operations.js
src/utils/function/lookupOptions.js
src/validations/Employer.js
src/validations/Student.js
src/views/Batches/batchComponents/ProgramEnrollmentForm.jsx
src/views/Employers/EmployerComponents/EmploymentConnectionForm.jsx
src/views/OperationsModule/OperationComponents/CollegepitchesEdit.jsx
src/views/OperationsModule/OperationComponents/UpskillUpdate.jsx
src/views/Opportunities/OpportunityComponents/EmploymentConnectionForm.jsx
src/views/Students/StudentComponents/StudentForm.jsx

edit form crash and issue raised by deepak

---

src/views/OperationsModule/OperationComponents/UpskillUpdate.jsx

edit upskill page issue

---

src/common/commonFunctions.js
src/graphql/employer.js
src/views/Employers/Employer.jsx
src/views/Employers/EmployerComponents/EmploymentConnection.jsx
src/views/Employers/EmployerComponents/EmploymentConnections.jsx
src/views/Opportunities/Opportunity.jsx
src/views/Opportunities/OpportunityComponents/EmploymentConnection.jsx

Targets #https://medhaofficial.atlassian.net/jira/software/projects/SIS/boards/1/backlog?assignee=712020%3Ade66f2c8-5ac5-4526-b4d9-514c6713ffa1&selectedIssue=SIS-153

limited access for edit and delete-> employers and opportunity

---

src/views/OperationsModule/OperationComponents/AlumniSearchBar.jsx
src/views/OperationsModule/OperationComponents/CollegePitchSearch.jsx
src/views/OperationsModule/OperationComponents/OpsSearchBar.js
src/views/OperationsModule/OperationComponents/TotSearchBar.jsx
src/views/OperationsModule/OperationComponents/UpskillSearchBar.jsx

search button alignment change in ops

---

src/views/Batches/Batches.jsx
src/views/Calendar/calendarComponents/ViewEvent.js
src/views/Calendar/calendarComponents/calendarActions.js
src/views/OperationsModule/OperationComponents/AlumniSearchBar.jsx
src/views/OperationsModule/OperationComponents/CollegePitchSearch.jsx
src/views/OperationsModule/OperationComponents/OpsSearchBar.js
src/views/OperationsModule/OperationComponents/TotSearchBar.jsx
src/views/OperationsModule/OperationComponents/UpskillSearchBar.jsx
src/views/Students/Students.jsx

Targets #https://medhaofficial.atlassian.net/browse/SIS-123

calendar changes 

---

src/views/Calendar/calendarComponents/ViewEvent.js
src/views/Calendar/calendarComponents/calendarActions.js

Targets #https://medhaofficial.atlassian.net/browse/SIS-123

new calendar updates

---

src/views/OperationsModule/OperationComponents/UploadFile.jsx
src/views/OperationsModule/UploadFiles/TotUpload.jsx

last changes for ops upload

---

src/views/OperationsModule/OperationComponents/UploadFile.jsx
src/views/OperationsModule/UploadFiles/TotUpload.jsx

last spm=inner change

---

src/views/Students/MassEdit/AlumMassEdit.jsx
src/views/Students/MassEdit/EmploymentmassEdit.jsx

Added file

---

src/graphql/operations.js
src/utils/Form/FormController.jsx
src/utils/Form/SelectSearchLookUp.jsx
src/views/OperationsModule/OperationComponents/Mentorship/MentorBulkAdd.jsx
src/views/OperationsModule/OperationComponents/Mentorship/MentorBulkrow.js
src/views/OperationsModule/OperationComponents/Mentorship/UpdateMentorship.jsx
src/views/OperationsModule/OperationComponents/OperationDataupdateform.jsx

feild activity edit form

---

src/views/OperationsModule/OperationComponents/Totdatafield.jsx
src/views/OperationsModule/Operations.jsx

added new entry edit form

---

src/graphql/batches.js
src/graphql/institutes.js
src/graphql/operations.js
src/utils/function/lookupOptions.js
src/views/OperationsModule/OperationComponents/CheckValuesOpsUploadedData.jsx
src/views/OperationsModule/OperationComponents/CollegePitchdata.jsx
src/views/OperationsModule/OperationComponents/DteUpskilingBulk.js
src/views/OperationsModule/OperationComponents/Mentorship/MentorBulkAdd.jsx
src/views/OperationsModule/OperationComponents/Mentorship/MentorBulkrow.js
src/views/OperationsModule/OperationComponents/Mentorship/MentorshipSearchbar.jsx
src/views/OperationsModule/OperationComponents/Mentorship/MentorshipdataField.jsx
src/views/OperationsModule/OperationComponents/Mentorship/UpdateMentorship.jsx
src/views/OperationsModule/OperationComponents/RowsData.js
src/views/OperationsModule/OperationComponents/Totdatafield.jsx
src/views/OperationsModule/OperationComponents/UploadFile.jsx
src/views/OperationsModule/OperationComponents/UpskillUpdate.jsx
src/views/OperationsModule/OperationComponents/UserTotRowdata.js
src/views/OperationsModule/OperationComponents/operationsActions.js
src/views/OperationsModule/Operations.jsx
src/views/OperationsModule/UploadFiles/CheckTot.jsx
src/views/OperationsModule/UploadFiles/TotUpload.jsx

added ops upload feature

---

src/graphql/batches.js
src/utils/function/lookupOptions.js
src/views/OperationsModule/OperationComponents/UploadFile.jsx

program enrollment issue

---

src/views/OperationsModule/OperationComponents/CheckValuesOpsUploadedData.jsx
src/views/OperationsModule/OperationComponents/OperationDataupdateform.jsx
src/views/OperationsModule/OperationComponents/UploadFile.jsx
src/views/OperationsModule/Operations.jsx

flow changes

---

src/views/OperationsModule/OperationComponents/UploadFile.jsx

upload file

---

src/views/OperationsModule/OperationComponents/Alumuniqueriesdata.jsx
src/views/OperationsModule/OperationComponents/CollegePitchdata.jsx
src/views/OperationsModule/OperationComponents/Opsdatafeilds.jsx
src/views/OperationsModule/OperationComponents/Totdatafield.jsx
src/views/OperationsModule/OperationComponents/Upskillingdatafield.jsx
src/views/OperationsModule/Operations.jsx

Edit form changes

---

src/views/OperationsModule/OperationComponents/Mentorship/MentorBulkAdd.jsx
src/views/OperationsModule/OperationComponents/Mentorship/MentorBulkrow.js
src/views/Students/StudentComponents/MassEdit.jsx

Mentoship data changes and alum data change

---

src/views/OperationsModule/OperationComponents/UploadFile.jsx
src/views/OperationsModule/UploadFiles/TotUpload.jsx

Added chnages for file upload in mass upload

---

src/views/Students/StudentComponents/MassEmployerUpload.jsx
src/views/Students/StudentComponents/ModalShowmassedit.jsx

number of intership hour shoul be 0 when student dropped out

---

src/views/Students/MassEdit/AlumMassEdit.jsx
src/views/Students/StudentComponents/StudentActions.js

Changes done for mass edit

---

src/utils/Form/FormController.jsx
src/utils/Form/SelectLookupAsync.jsx
src/views/Students/StudentComponents/MassEmployerUpload.jsx
src/views/Students/StudentComponents/StudentsSearchBar.jsx

Targets #{issueid}
- [] Wrote tests

Naresh dev

---

src/components/content/Avatar.jsx
src/components/content/Table.jsx
src/views/OperationsModule/OperationComponents/UploadFile.jsx
src/views/Students/MassEdit/AlumMassEdit.jsx
src/views/Students/MassEdit/EmploymentmassEdit.jsx
src/views/Students/StudentComponents/MassEmployerUpload.jsx
src/views/Students/Students.jsx

mass edit feature

---

src/views/OperationsModule/UploadFiles/TotUpload.jsx

added changes in tot upload

---

src/views/Students/MassEdit/EmploymentmassEdit.jsx

Added loader in mass edit

---

src/views/Students/MassEdit/AlumMassEdit.jsx
src/views/Students/MassEdit/EmploymentmassEdit.jsx

Start date end date

---

src/graphql/employer.js
src/views/Employers/EmployerComponents/EmployerForm.jsx

Nested drop down employment

---

src/graphql/batches.js
src/graphql/operations.js
src/views/OperationsModule/OperationComponents/Mentorship/MentorBulkAdd.jsx
src/views/OperationsModule/OperationComponents/Mentorship/MentorBulkrow.js
src/views/OperationsModule/OperationComponents/Mentorship/MentorshipdataField.jsx
src/views/OperationsModule/OperationComponents/Mentorship/UpdateMentorship.jsx
src/views/OperationsModule/OperationComponents/UploadFile.jsx
src/views/OperationsModule/OperationComponents/operationsActions.js
src/views/OperationsModule/Operations.jsx
src/views/OperationsModule/UploadFiles/TotUpload.jsx

Mentorship

---

src/views/Employers/EmployerComponents/EmployerForm.jsx

Added serc file

---

src/views/Students/MassEdit/AlumMassEdit.jsx
src/views/Students/MassEdit/EmploymentmassEdit.jsx
src/views/Students/MassEdit/MassEdit.jsx
src/views/Students/MassEdit/MassEmployerUpload.jsx
src/views/Students/MassEdit/ModalMassEdit.jsx
src/views/Students/MassEdit/ModaltoSelectBulkMassEdit.jsx
src/views/Students/StudentComponents/StudentActions.js
src/views/Students/StudentComponents/StudentForm.jsx
src/views/Students/Students.jsx

console and some ui modification

---

src/views/Employers/EmployerComponents/EmployerForm.jsx

indexing issue in dropdown

---

src/views/OperationsModule/OperationComponents/Mentorship/MentorBulkAdd.jsx
src/views/OperationsModule/OperationComponents/Mentorship/MentorBulkrow.js
src/views/OperationsModule/OperationComponents/Mentorship/UpdateMentorship.jsx

upto 10 character should allow

---

src/views/Students/Students.jsx

resolved sort issue

---

src/views/OperationsModule/Operations.jsx
src/views/Students/MassEdit/AlumMassEdit.jsx
src/views/Students/MassEdit/ModalMassEdit.jsx
src/views/Students/MassEdit/ModaltoSelectBulkMassEdit.jsx
src/views/Students/Students.jsx

Mass editsortissue

---

src/views/OperationsModule/OperationComponents/UploadFile.jsx
src/views/OperationsModule/Operations.jsx

Added last changes

---

src/views/Batches/Batch.jsx
src/views/Batches/Batches.jsx
src/views/Batches/batchActions.js

Targets #[{issueid}](https://medhaofficial.atlassian.net/browse/SIS-166)https://medhaofficial.atlassian.net/browse/SIS-166

added batch email trigger

---

src/components/layout/Sidebar.jsx
src/views/Dashboard/Home.jsx

changes in the layout

---

src/App.jsx
src/components/layout/Sidebar.jsx

Added layout changes

---

src/views/OperationsModule/OperationComponents/CheckValuesOpsUploadedData.jsx
src/views/OperationsModule/OperationComponents/UploadFile.jsx
src/views/OperationsModule/Operations.jsx

changes in activity type

---

src/views/OperationsModule/OperationComponents/CheckValuesOpsUploadedData.jsx
src/views/OperationsModule/OperationComponents/UploadFile.jsx
src/views/OperationsModule/UploadFiles/CheckTot.jsx
src/views/OperationsModule/UploadFiles/TotUpload.jsx

Added age check in tot

---

src/views/OperationsModule/OperationComponents/CheckValuesOpsUploadedData.jsx
src/views/OperationsModule/OperationComponents/UploadFile.jsx

added validation

---

src/views/OperationsModule/OperationComponents/CheckValuesOpsUploadedData.jsx
src/views/OperationsModule/UploadFiles/CheckTot.jsx
src/views/OperationsModule/UploadFiles/TotUpload.jsx

validation for no data

---

src/views/OperationsModule/UploadFiles/TotUpload.jsx

no participAant

---

src/graphql/batches.js
src/views/OperationsModule/OperationComponents/CheckValuesOpsUploadedData.jsx
src/views/OperationsModule/OperationComponents/Mentorship/MentorBulkAdd.jsx
src/views/OperationsModule/OperationComponents/Mentorship/MentorBulkrow.js
src/views/OperationsModule/OperationComponents/Mentorship/MentorshipdataField.jsx
src/views/OperationsModule/OperationComponents/Mentorship/UpdateMentorship.jsx
src/views/OperationsModule/OperationComponents/OperationDataupdateform.jsx
src/views/OperationsModule/OperationComponents/Opsdatafeilds.jsx
src/views/OperationsModule/OperationComponents/TotEdit.jsx
src/views/OperationsModule/OperationComponents/Totdatafield.jsx
src/views/OperationsModule/OperationComponents/UploadFile.jsx
src/views/OperationsModule/OperationComponents/UserTot.jsx
src/views/OperationsModule/OperationComponents/operationsActions.js
src/views/OperationsModule/Operations.jsx
src/views/OperationsModule/UploadFiles/CheckTot.jsx
src/views/OperationsModule/UploadFiles/TotUpload.jsx

Ops upload

---

src/views/Students/MassEdit/EmploymentmassEdit.jsx

Added changes for mass employer edit

---

src/views/Batches/Batch.jsx
src/views/Batches/Batches.jsx
src/views/Batches/batchActions.js

Targets #https://medhaofficial.atlassian.net/browse/SIS-166

batch email changes

---

src/views/Employers/EmployerComponents/EmployerForm.jsx
src/views/Students/MassEdit/EmploymentmassEdit.jsx

added changes for mass employer

---

src/views/OperationsModule/OperationComponents/Mentorship/MentorBulkAdd.jsx
src/views/OperationsModule/OperationComponents/Mentorship/MentorshipdataField.jsx
src/views/OperationsModule/OperationComponents/Mentorship/UpdateMentorship.jsx

mentosrship changes

---

src/graphql/employer.js
src/views/Employers/EmployerComponents/EmployerForm.jsx

Industrychanges

---

src/validations/OperationsValidation.js
src/views/OperationsModule/OperationComponents/Mentorship/MentorBulkAdd.jsx
src/views/OperationsModule/OperationComponents/Mentorship/MentorshipdataField.jsx
src/views/OperationsModule/OperationComponents/Mentorship/UpdateMentorship.jsx

Added validation for mentorship update form

---

src/views/Dashboard/Home.jsx
src/views/Dashboard/components/LatestActivity.jsx
src/views/Dashboard/components/LatestActivityDetail.jsx

Changes made for Addign widget to the dashBoard

---

src/graphql/employer.js
src/views/Dashboard/components/LatestActivity.jsx
src/views/Employers/EmployerComponents/EmployerForm.jsx

Added changes for latest activity

---

src/assets/scss/main.scss
src/views/OperationsModule/OperationComponents/Mentorship/MentorBulkrow.js
src/views/OperationsModule/OperationComponents/Mentorship/MentorshipSearchbar.jsx
src/views/OperationsModule/OperationComponents/Mentorship/UpdateMentorship.jsx

Last changes for mentorship

---

src/graphql/address.js
src/views/Address/addressActions.js
src/views/OperationsModule/OperationComponents/Mentorship/UpdateMentorship.jsx

changes for cities data

---

src/views/OperationsModule/OperationComponents/OperationDataupdateform.jsx

Added chnages in update file

---

src/views/OperationsModule/OperationComponents/CheckValuesOpsUploadedData.jsx
src/views/OperationsModule/OperationComponents/OperationDataupdateform.jsx
src/views/OperationsModule/OperationComponents/UploadFile.jsx
src/views/Students/Students.jsx

Chnages in student module and operation module

---

src/utils/LatestChange/Api.js
src/views/Address/addressActions.js
src/views/Batches/Batch.jsx
src/views/Batches/batchComponents/BatchForm.jsx
src/views/Batches/batchComponents/ProgramEnrollmentForm.jsx
src/views/Batches/batchComponents/Sessions.jsx
src/views/Calendar/calendarComponents/EventForm.jsx
src/views/Dashboard/components/LatestActivityDetail.jsx
src/views/Employers/EmployerComponents/OpportunityForm.jsx
src/views/Institutions/InstitutionComponents/InstitutionForm.jsx
src/views/Institutions/InstitutionComponents/ProgramEnrollmentForm.jsx
src/views/OperationsModule/OperationComponents/CollegepitchesEdit.jsx
src/views/OperationsModule/OperationComponents/OperationDataupdateform.jsx
src/views/OperationsModule/OperationComponents/Opsdatafeilds.jsx
src/views/Opportunities/OpportunityComponents/EmploymentConnectionForm.jsx
src/views/Students/StudentComponents/AlumniServiceForm.jsx
src/views/Students/StudentComponents/EmploymentConnectionForm.jsx
src/views/Students/StudentComponents/ProgramEnrollmentForm.jsx

changes for latest activity

---

src/views/OperationsModule/OperationComponents/Mentorship/MentorBulkAdd.jsx
src/views/OperationsModule/OperationComponents/OperationCreateform.jsx

Added changes for ops add

---

src/validations/OperationsValidation.js

changes for contact detail

---

src/graphql/student.js
src/views/Students/MassEdit/AlumMassEdit.jsx
src/views/Students/StudentComponents/StudentActions.js

changes made for mass edit

---

src/utils/function/indtsryValues.js
src/views/Employers/EmployerComponents/EmployerForm.jsx

changes made new industry heirarchy

---

src/graphql/batches.js
src/graphql/student.js
src/validations/Calendar.js
src/views/Calendar/calendarComponents/EventForm.jsx
src/views/OperationsModule/OperationComponents/CheckValuesOpsUploadedData.jsx
src/views/OperationsModule/OperationComponents/UploadFile.jsx
src/views/Students/Students.jsx

Targets #https://medhaofficial.atlassian.net/browse/SIS-177

Locations and participants optional

---

package-lock.json
package.json
src/graphql/student.js

fixed build errors

---

src/assets/scss/main.scss
src/views/Employers/EmployerComponents/EmployerForm.jsx

css changes

---

src/graphql/operations.js

last change

---

src/App.jsx
src/assets/scss/main.scss
src/views/Employers/EmployerComponents/EmployerForm.jsx
src/views/Employers/EmployerComponents/NestedDropdown.jsx

Added industry changes:

---

src/utils/LatestChange/Api.js
src/views/Batches/batchComponents/ProgramEnrollmentForm.jsx
src/views/Dashboard/components/LatestActivity.jsx
src/views/Dashboard/components/LatestActivityDetail.jsx
src/views/Employers/EmployerComponents/EmploymentConnectionForm.jsx
src/views/Employers/EmployerComponents/OpportunityForm.jsx
src/views/Institutions/InstitutionComponents/ProgramEnrollmentForm.jsx
src/views/Opportunities/OpportunityComponents/EmploymentConnectionForm.jsx
src/views/Students/StudentComponents/EmploymentConnectionForm.jsx
src/views/Students/StudentComponents/ProgramEnrollmentForm.jsx

Latest activity

---

src/utils/function/lookupOptions.js
src/views/Batches/batchComponents/BatchSearchBar.jsx
src/views/Employers/EmployerComponents/EmployerSearchBar.jsx
src/views/Institutions/InstitutionComponents/InstitutionSearchBar.jsx
src/views/OperationsModule/OperationComponents/OpsSearchBar.js
src/views/OperationsModule/OperationComponents/UpskillSearchBar.jsx
src/views/Opportunities/OpportunityComponents/OpportunitySearchBar.jsx
src/views/Students/StudentComponents/StudentsSearchBar.jsx

Search dropdown for srm in all module

---

src/graphql/operations.js
src/views/OperationsModule/Operations.jsx

Fixed active count

---

src/graphql/student.js

role added in student

---

src/utils/LatestChange/Api.js
src/views/Batches/batchComponents/ProgramEnrollmentForm.jsx
src/views/Dashboard/components/LatestActivity.jsx
src/views/Dashboard/components/LatestActivityDetail.jsx
src/views/Employers/EmployerComponents/EmploymentConnectionForm.jsx
src/views/Employers/EmployerComponents/OpportunityForm.jsx
src/views/Institutions/InstitutionComponents/ProgramEnrollmentForm.jsx
src/views/Opportunities/OpportunityComponents/EmploymentConnectionForm.jsx
src/views/Students/StudentComponents/EmploymentConnectionForm.jsx
src/views/Students/StudentComponents/ProgramEnrollmentForm.jsx

Reverts gitmedha/sis-frontend#1012

Revert "Latest activity"

---

src/utils/LatestChange/Api.js
src/views/Batches/batchComponents/ProgramEnrollmentForm.jsx
src/views/Dashboard/components/LatestActivity.jsx
src/views/Dashboard/components/LatestActivityDetail.jsx
src/views/Employers/EmployerComponents/EmploymentConnectionForm.jsx
src/views/Employers/EmployerComponents/OpportunityForm.jsx
src/views/Institutions/InstitutionComponents/ProgramEnrollmentForm.jsx
src/views/Opportunities/OpportunityComponents/EmploymentConnectionForm.jsx
src/views/Students/StudentComponents/EmploymentConnectionForm.jsx
src/views/Students/StudentComponents/ProgramEnrollmentForm.jsx

Reverts gitmedha/sis-frontend#1017

Revert "Revert "Latest activity""

---

src/App.jsx
src/assets/scss/main.scss
src/components/layout/Sidebar.jsx
src/utils/LatestChange/Api.js
src/views/Dashboard/components/LatestActivity.jsx
src/views/Dashboard/components/LatestActivityDetail.jsx
src/views/Employers/Employer.jsx
src/views/Employers/EmployerComponents/EmployerForm.jsx
src/views/Employers/EmployerComponents/employerAction.js
src/views/Employers/Employers.jsx
src/views/Institutions/InstitutionComponents/InstitutionForm.jsx
src/views/Institutions/Institutions.jsx
src/views/OperationsModule/OperationComponents/AllumuniEdit.jsx
src/views/OperationsModule/OperationComponents/CollegepitchesEdit.jsx
src/views/OperationsModule/OperationComponents/OperationDataupdateform.jsx
src/views/OperationsModule/Operations.jsx
src/views/Opportunities/Opportunities.jsx
src/views/Opportunities/OpportunityComponents/OpportunityForm.jsx
src/views/Students/Student.jsx
src/views/Students/StudentComponents/AlumniServiceForm.jsx
src/views/Students/StudentComponents/EmploymentConnectionForm.jsx
src/views/Students/StudentComponents/StudentForm.jsx

Adding changes for mentorship data

---

src/views/Students/StudentComponents/StudentForm.jsx
src/views/Students/Students.jsx

Added src file changes

---

src/views/Dashboard/components/LatestActivity.jsx
src/views/Students/StudentComponents/ProgramEnrollmentForm.jsx

date change

---

src/assets/scss/main.scss
src/views/Batches/batchComponents/ProgramEnrollmentForm.jsx
src/views/Dashboard/components/LatestActivityDetail.jsx
src/views/Employers/Employer.jsx
src/views/Employers/EmployerComponents/EmployerForm.jsx
src/views/Employers/Employers.jsx
src/views/Institutions/Institution.jsx
src/views/Institutions/InstitutionComponents/InstitutionForm.jsx
src/views/Institutions/Institutions.jsx
src/views/Opportunities/Opportunities.jsx
src/views/Opportunities/Opportunity.jsx
src/views/Opportunities/OpportunityComponents/OpportunityForm.jsx
src/views/Students/Student.jsx
src/views/Students/StudentComponents/ProgramEnrollmentForm.jsx
src/views/Students/StudentComponents/StudentForm.jsx
src/views/Students/Students.jsx

style changes

---

src/views/OperationsModule/OperationComponents/AllumuniEdit.jsx
src/views/OperationsModule/OperationComponents/Alumuniqueriesdata.jsx
src/views/OperationsModule/OperationComponents/CollegePitchdata.jsx
src/views/OperationsModule/OperationComponents/CollegepitchesEdit.jsx
src/views/OperationsModule/OperationComponents/Mentorship/MentorshipdataField.jsx
src/views/OperationsModule/OperationComponents/Mentorship/UpdateMentorship.jsx
src/views/OperationsModule/OperationComponents/OperationDataupdateform.jsx
src/views/OperationsModule/OperationComponents/Opsdatafeilds.jsx
src/views/OperationsModule/OperationComponents/TotEdit.jsx
src/views/OperationsModule/OperationComponents/Totdatafield.jsx
src/views/OperationsModule/OperationComponents/UpskillUpdate.jsx
src/views/OperationsModule/OperationComponents/Upskillingdatafield.jsx
src/views/OperationsModule/Operations.jsx

ops changes

---

src/views/Employers/EmployerComponents/Details.jsx

Added detail feild changes

---

src/views/Batches/batchComponents/ProgramEnrollmentForm.jsx
src/views/Students/StudentComponents/ProgramEnrollmentForm.jsx

Added changes for batch name

---

src/views/OperationsModule/UploadFiles/TotUpload.jsx

change city

---

src/utils/function/indtsryValues.js
src/views/Employers/EmployerComponents/EmployerForm.jsx

Changes for industry

---

src/views/Employers/EmployerComponents/EmployerForm.jsx

Added changes for industry dropdown

---

src/validations/Calendar.js
src/views/Calendar/calendarComponents/EventForm.jsx

Targets #https://medhaofficial.atlassian.net/browse/SIS-177

location and particiepents optional

---

src/views/Employers/EmployerComponents/EmploymentConnectionForm.jsx
src/views/Opportunities/OpportunityComponents/EmploymentConnectionForm.jsx
src/views/Students/StudentComponents/EmploymentConnectionForm.jsx

Targets #https://medhaofficial.atlassian.net/browse/SIS-173

added freelance -> employment connection forms

---

src/graphql/operations.js
src/views/OperationsModule/OperationComponents/TotEdit.jsx
src/views/OperationsModule/OperationComponents/Totdatafield.jsx
src/views/OperationsModule/OperationComponents/UserTot.jsx
src/views/OperationsModule/OperationComponents/UserTotRowdata.js
src/views/OperationsModule/UploadFiles/CheckTot.jsx
src/views/OperationsModule/UploadFiles/TotUpload.jsx

Added tot changes

---

src/views/Employers/EmployerComponents/EmployerForm.jsx

changes for irrigationa nd diversified

---

src/views/OperationsModule/OperationComponents/Mentorship/UpdateMentorship.jsx
src/views/OperationsModule/Operations.jsx
src/views/OperationsModule/UploadFiles/CheckMentorship.jsx
src/views/OperationsModule/UploadFiles/MentorShip/Check.jsx
src/views/OperationsModule/UploadFiles/MentorShip/MentorshipUpload.jsx
src/views/OperationsModule/UploadFiles/Pitching/PitchingUpload.jsx
src/views/OperationsModule/UploadFiles/TOT/CheckTot.jsx
src/views/OperationsModule/UploadFiles/TOT/TotUpload.jsx
src/views/OperationsModule/UploadFiles/Upskilling/UpskillingUpload.jsx

Mentorship excel uplaod

---

src/views/Employers/EmployerComponents/EmployerForm.jsx

sorting in industry

---

src/common/commonFunctions.js
src/views/OperationsModule/OperationComponents/UploadFile.jsx
src/views/OperationsModule/OperationComponents/operationsActions.js
src/views/OperationsModule/Operations.jsx
src/views/OperationsModule/UploadFiles/MentorShip/MentorshipUpload.jsx
src/views/OperationsModule/UploadFiles/Pitching/Check.jsx
src/views/OperationsModule/UploadFiles/Pitching/PitchingUpload.jsx
src/views/OperationsModule/UploadFiles/Upskilling/UpskillingUpload.jsx

Pitching excel upload

---

src/views/OperationsModule/OperationComponents/TotEdit.jsx

trainer 2 validation

---

src/graphql/student.js
src/views/OperationsModule/OperationComponents/UploadFile.jsx
src/views/OperationsModule/OperationComponents/operationsActions.js
src/views/OperationsModule/Operations.jsx
src/views/OperationsModule/UploadFiles/Upskilling/Check.jsx
src/views/OperationsModule/UploadFiles/Upskilling/UpskillingUpload.jsx

student upskilling excel upload

---

src/validations/Calendar.js
src/validations/Student.js
src/views/OperationsModule/OperationComponents/TotEdit.jsx
src/views/OperationsModule/OperationComponents/Totdatafield.jsx
src/views/OperationsModule/UploadFiles/CheckMentorship.jsx
src/views/OperationsModule/UploadFiles/TOT/CheckTot.jsx
src/views/OperationsModule/UploadFiles/TOT/TotUpload.jsx
src/views/Students/StudentComponents/AlumniServiceForm.jsx

Reverts gitmedha/sis-frontend#1050

Revert "Staging sis 188"

---

src/validations/Student.js
src/views/OperationsModule/UploadFiles/CheckTot.jsx
src/views/OperationsModule/UploadFiles/TotUpload.jsx
src/views/Students/StudentComponents/AlumniServiceForm.jsx

Added Chnages for tot and alumniservice form

---

src/views/OperationsModule/OperationComponents/UpskillUpdate.jsx
src/views/OperationsModule/UploadFiles/Upskilling/UpskillingUpload.jsx

Added upskilling chnages

---

src/utils/LatestChange/Api.js
src/views/Batches/Batch.jsx
src/views/Batches/Batches.jsx
src/views/Batches/batchComponents/BatchForm.jsx
src/views/Employers/Employer.jsx
src/views/Employers/EmployerComponents/EmployerForm.jsx
src/views/Employers/EmployerComponents/EmploymentConnectionForm.jsx
src/views/Employers/EmployerComponents/employerAction.js
src/views/Institutions/InstitutionComponents/InstitutionForm.jsx
src/views/Institutions/InstitutionComponents/ProgramEnrollments.jsx
src/views/OperationsModule/OperationComponents/CollegepitchesEdit.jsx
src/views/OperationsModule/OperationComponents/Mentorship/UpdateMentorship.jsx
src/views/OperationsModule/OperationComponents/OperationDataupdateform.jsx
src/views/OperationsModule/OperationComponents/Opsdatafeilds.jsx
src/views/OperationsModule/OperationComponents/UpskillUpdate.jsx
src/views/OperationsModule/UploadFiles/Pitching/PitchingUpload.jsx
src/views/OperationsModule/UploadFiles/Upskilling/UpskillingUpload.jsx
src/views/Opportunities/OpportunityComponents/EmploymentConnectionForm.jsx
src/views/Opportunities/OpportunityComponents/OpportunityForm.jsx
src/views/Students/StudentComponents/EmploymentConnectionForm.jsx

Added changes for lates activity

---

src/assets/scss/main.scss
src/views/Employers/EmployerComponents/EmployerForm.jsx
src/views/Employers/EmployerComponents/src/views/Employers/EmployerComponents/NestedDropdown.jsx

Added changes for industry heirarchy dropdown

---

src/views/Dashboard/components/LatestActivity.jsx
src/views/OperationsModule/Operations.jsx
src/views/OperationsModule/UploadFiles/TOT/TotUpload.jsx

changes made for tot template and latest activity

---

src/views/Students/MassEdit/MassEdit.jsx

add some input fields in input valdiation for alumni-engagement

---

src/views/OperationsModule/UploadFiles/Upskilling/UpskillingUpload.jsx

changes for closing the poppu

---

src/components/content/Utils.jsx

fix attendance ui

---

src/assets/scss/main.scss
src/views/Batches/Batch.jsx
src/views/Batches/batchActions.js
src/views/Employers/EmployerComponents/src/views/Employers/EmployerComponents/NestedDropdown.jsx
src/views/OperationsModule/OperationComponents/OperationDataupdateform.jsx
src/views/Students/StudentComponents/AlumniServiceForm.jsx

Manual reminder button

---

src/views/Employers/EmployerComponents/src/views/Employers/EmployerComponents/NestedDropdown.jsx

fixed bug in searchable dropdown

---

src/views/Students/StudentComponents/ProgramEnrollment.jsx
src/views/Students/StudentComponents/ProgramEnrollmentForm.jsx

Added commit for sis-206

---

src/views/Opportunities/OpportunityComponents/Details.jsx
src/views/Opportunities/OpportunityComponents/OpportunityForm.jsx

Added change for opprtunity module

---

src/components/content/Table.jsx
src/views/Employers/Employers.jsx

fix ui allignment in table and employers module

---

src/views/Employers/EmployerComponents/src/views/Employers/EmployerComponents/NestedDropdown.jsx

make dropdown searchable

---

src/validations/Employer.js
src/views/Employers/EmployerComponents/EmploymentConnection.jsx
src/views/Employers/EmployerComponents/EmploymentConnectionForm.jsx
src/views/Opportunities/OpportunityComponents/EmploymentConnection.jsx
src/views/Opportunities/OpportunityComponents/EmploymentConnectionForm.jsx
src/views/Opportunities/OpportunityComponents/OpportunityForm.jsx

Opportunites module/sis 209

---

src/validations/Employer.js
src/views/Employers/EmployerComponents/EmployerForm.jsx
src/views/Students/StudentComponents/StudentForm.jsx

Added src file for the sis-196

---

src/views/Batches/batchComponents/BatchForm.jsx

CHANGES MADE FOR SIS-210

---

src/views/Batches/batchActions.js
src/views/Batches/batchComponents/BatchForm.jsx

Added changes for institute dropdown

---

src/views/Batches/batchComponents/BatchForm.jsx
src/views/Batches/batchComponents/ProgramEnrollmentForm.jsx
src/views/OperationsModule/OperationComponents/Mentorship/MentorshipSearchbar.jsx
src/views/OperationsModule/OperationComponents/Mentorship/UpdateMentorship.jsx
src/views/OperationsModule/OperationComponents/OperationDataupdateform.jsx
src/views/OperationsModule/OperationComponents/UploadFile.jsx
src/views/OperationsModule/OperationComponents/UserTot.jsx
src/views/OperationsModule/Operations.jsx
src/views/Opportunities/OpportunityComponents/EmploymentConnection.jsx
src/views/Students/MassEdit/AlumMassEdit.jsx
src/views/Students/MassEdit/ModalShowmassedit.jsx
src/views/Students/StudentComponents/ProgramEnrollmentForm.jsx

Added changes for institution dropdown

---

src/components/content/Table.jsx
src/views/Employers/Employers.jsx

fix Table ui

---

src/views/Batches/batchComponents/ProgramEnrollmentForm.jsx
src/views/Employers/EmployerComponents/EmployerForm.jsx
src/views/Employers/EmployerComponents/src/views/Employers/EmployerComponents/NestedDropdown.jsx
src/views/Students/StudentComponents/ProgramEnrollmentForm.jsx

Added changes for industry heirarchy

---

src/views/Employers/EmployerComponents/EmployerForm.jsx

Added changes for employer medha partner

---

src/validations/Opportunity.js
src/views/Opportunities/OpportunityComponents/OpportunityForm.jsx

made validation for sis-204

---

src/validations/Employer.js
src/validations/Opportunity.js
src/views/Batches/batchComponents/BatchForm.jsx
src/views/Batches/batchComponents/BatchSessionForm.jsx
src/views/Employers/EmployerComponents/EmployerForm.jsx
src/views/OperationsModule/OperationComponents/TotEdit.jsx
src/views/Opportunities/OpportunityComponents/OpportunityForm.jsx

Release changes for sis-193,202,203,204,205 206 and 210

---

src/views/Employers/EmployerComponents/EmployerForm.jsx

remove react-dropdown-tree-select

---

src/validations/Employer.js
src/validations/Student.js
src/views/Employers/EmployerComponents/EmploymentConnection.jsx
src/views/Employers/EmployerComponents/EmploymentConnectionForm.jsx
src/views/Opportunities/OpportunityComponents/EmploymentConnection.jsx
src/views/Opportunities/OpportunityComponents/EmploymentConnectionForm.jsx
src/views/Students/StudentComponents/EmploymentConnection.jsx
src/views/Students/StudentComponents/EmploymentConnectionForm.jsx

salary field label changed in employment connection module

---

src/views/OperationsModule/UploadFiles/MentorShip/MentorshipUpload.jsx
src/views/OperationsModule/UploadFiles/Pitching/PitchingUpload.jsx

Added changes for student upakilllig bulk excel upload

---

src/components/content/TabPicker.jsx
src/views/OperationsModule/Operations.jsx

add student outreach tab in sa module

---

src/views/Opportunities/OpportunityComponents/EmploymentConnections.jsx

Added changes for employment connection data

---

src/views/Students/MassEdit/MassEdit.jsx

Added src file for the alumni engament change

---

src/views/Students/MassEdit/MassEdit.jsx

added srf file for mass edit changes

---

src/views/OperationsModule/OperationComponents/Mentorship/MentorBulkAdd.jsx
src/views/OperationsModule/OperationComponents/Mentorship/MentorshipdataField.jsx
src/views/OperationsModule/UploadFiles/MentorShip/MentorshipUpload.jsx
src/views/OperationsModule/UploadFiles/Upskilling/UpskillingUpload.jsx

Added changes for excel upload module

---

src/views/OperationsModule/OperationComponents/TotEdit.jsx

removed validation for the tot edit

---

src/App.jsx

Added changes for userpermission

---

src/views/Batches/batchComponents/BatchForm.jsx

institute problem

---

src/views/Students/StudentComponents/ProgramEnrollmentForm.jsx
src/views/Students/StudentComponents/StudentActions.js

fixed issue for instituition dropdowns for students->program enrollement form

---

src/views/Students/MassEdit/AlumMassEdit.jsx
src/views/Students/MassEdit/MassEdit.jsx
src/views/Students/StudentComponents/EmploymentConnectionForm.jsx

Added changes for sis 215 and 216

---

src/views/Students/MassEdit/AlumMassEdit.jsx
src/views/Students/MassEdit/MassEdit.jsx

role changes

---

src/views/OperationsModule/OperationComponents/Mentorship/MentorBulkAdd.jsx
src/views/OperationsModule/Operations.jsx

Added chnages for mentorship

---

src/views/Calendar/calendarComponents/ViewEvent.js
src/views/Dashboard/components/LatestActivity.jsx
src/views/Opportunities/OpportunityComponents/OpportunityForm.jsx

Added changes in opprtunity module

---

src/views/OperationsModule/OperationComponents/studentOutreachSearchBar.jsx

refactor search field

---

src/views/Students/StudentComponents/Details.jsx

Added changes for removing plan after current course

---

src/views/OperationsModule/OperationComponents/Mentorship/MentorshipSearchbar.jsx
src/views/OperationsModule/OperationComponents/OpsSearchBar.js
src/views/OperationsModule/OperationComponents/TotSearchBar.jsx

Added chnages for multiple filter dropdown

---

src/views/Students/MassEdit/AlumMassEdit.jsx
src/views/Students/MassEdit/MassEdit.jsx

role added for mass edit

---

src/views/Dashboard/components/LatestActivity.jsx
src/views/OperationsModule/OperationComponents/Mentorship/MentorBulkAdd.jsx
src/views/OperationsModule/OperationComponents/Mentorship/MentorBulkrow.js

added changes for sis-220

---

src/views/Students/MassEdit/AlumMassEdit.jsx

Added changes for sis-219

---

src/views/OperationsModule/OperationComponents/Mentorship/MentorBulkAdd.jsx
src/views/OperationsModule/OperationComponents/Mentorship/MentorBulkrow.js
src/views/Students/MassEdit/AlumMassEdit.jsx
src/views/Students/StudentComponents/ProgramEnrollment.jsx

Added changes for sis deployment

---

src/views/OperationsModule/OperationComponents/Mentorship/MentorBulkAdd.jsx

addded changes for mentorship module:

---

src/views/OperationsModule/OperationComponents/operationsActions.js
src/views/OperationsModule/Operations.jsx
src/views/OperationsModule/UploadFiles/CheckMentorship.jsx
src/views/OperationsModule/UploadFiles/MentorShip/Check.jsx
src/views/OperationsModule/UploadFiles/MentorShip/MentorshipUpload.jsx
src/views/OperationsModule/UploadFiles/Pitching/Check.jsx
src/views/OperationsModule/UploadFiles/Pitching/PitchingUpload.jsx
src/views/OperationsModule/UploadFiles/TOT/CheckTot.jsx
src/views/OperationsModule/UploadFiles/TOT/TotUpload.jsx
src/views/OperationsModule/UploadFiles/Upskilling/Check.jsx
src/views/OperationsModule/UploadFiles/Upskilling/UpskillingUpload.jsx

added changes for ops upload module

---

src/views/OperationsModule/Operations.jsx

added changes for sis-225

---

src/views/OperationsModule/OperationComponents/StudentOutreach/AddStudentOutreach.jsx
src/views/OperationsModule/OperationComponents/StudentOutreach/FormFields/DateField.jsx
src/views/OperationsModule/OperationComponents/StudentOutreach/FormFields/NumberField.jsx
src/views/OperationsModule/OperationComponents/StudentOutreach/FormFields/SelectField.jsx
src/views/OperationsModule/OperationComponents/StudentOutreach/FormFields/TextField.jsx
src/views/OperationsModule/OperationComponents/StudentOutreach/StudentOutreachRowdata.jsx
src/views/OperationsModule/OperationComponents/StudentOutreach/hooks/useFormValidation.js
src/views/OperationsModule/OperationComponents/StudentOutreach/utils/constants.js

changes for not displaying start date and end date and ui changes

---

src/views/OperationsModule/OperationComponents/StudentOutreach/FormFields/DateField.jsx
src/views/OperationsModule/OperationComponents/StudentOutreach/FormFields/NumberField.jsx
src/views/OperationsModule/OperationComponents/StudentOutreach/FormFields/TextField.jsx

ui changes for input box

---

src/views/OperationsModule/Operations.jsx

remove student outreach

---

src/views/OperationsModule/OperationComponents/StudentOutreach/AddStudentOutreach.jsx
src/views/OperationsModule/OperationComponents/StudentOutreach/StudentOutreachRowdata.jsx

make state reset for every category change

---

src/views/OperationsModule/Operations.jsx

Added changes for mentroship data

---

src/views/OperationsModule/OperationComponents/OpsSearchBar.js

Added changes in mentoship

---

src/components/content/Table.jsx
src/graphql/batches.js
src/views/Institutions/Institutions.jsx

added changes for # and name

---

src/graphql/operations.js
src/views/OperationsModule/OperationComponents/Mentorship/MentorBulkAdd.jsx
src/views/OperationsModule/OperationComponents/Mentorship/MentorBulkrow.js
src/views/OperationsModule/OperationComponents/Mentorship/MentorshipdataField.jsx
src/views/OperationsModule/OperationComponents/Mentorship/UpdateMentorship.jsx

Added changes for mentorship edit

---

src/views/OperationsModule/OperationComponents/TotSearchBar.jsx
src/views/OperationsModule/OperationComponents/UserTot.jsx
src/views/OperationsModule/Operations.jsx

added default search bar

---

src/views/OperationsModule/OperationComponents/Totdatafield.jsx
src/views/OperationsModule/OperationComponents/UserTot.jsx
src/views/OperationsModule/OperationComponents/UserTotRowdata.js

added new entry at the last in bulk add

---

src/views/OperationsModule/OperationComponents/UserTotRowdata.js

fixed the issue

---

src/views/OperationsModule/OperationComponents/Mentorship/MentorBulkrow.js
src/views/OperationsModule/Operations.jsx

capital name change

---

src/views/Employers/EmployerComponents/EmploymentConnectionForm.jsx
src/views/Students/StudentComponents/EmploymentConnectionForm.jsx

COmmit msg

---

src/views/Employers/EmployerComponents/EmploymentConnectionForm.jsx
src/views/Opportunities/OpportunityComponents/EmploymentConnectionForm.jsx
src/views/Students/MassEdit/EmploymentmassEdit.jsx
src/views/Students/MassEdit/MassEmployerUpload.jsx
src/views/Students/StudentComponents/EmploymentConnectionForm.jsx

Sis 216 new

---

src/graphql/user.js
src/utils/function/lookupOptions.js
src/views/Batches/batchComponents/BatchForm.jsx
src/views/Calendar/calendarComponents/EventForm.jsx
src/views/Institutions/InstitutionComponents/InstitutionForm.jsx
src/views/OperationsModule/OperationComponents/Mentorship/UpdateMentorship.jsx
src/views/OperationsModule/OperationComponents/OperationDataupdateform.jsx
src/views/OperationsModule/OperationComponents/TotEdit.jsx
src/views/OperationsModule/OperationComponents/UpskillUpdate.jsx
src/views/OperationsModule/OperationComponents/Upskillingdatafield.jsx
src/views/OperationsModule/OperationComponents/operationsActions.js
src/views/OperationsModule/UploadFiles/TOT/CheckTot.jsx
src/views/Opportunities/OpportunityComponents/OpportunityForm.jsx
src/views/Students/StudentComponents/StudentForm.jsx

Added changes for Assigned to feild if the srm is not in medha

---

src/views/Institutions/Institutions.jsx

Institution table N/A value for null cells

---

src/graphql/user.js
src/store/reducers/Operations/actions.js
src/utils/function/lookupOptions.js
src/views/OperationsModule/OperationComponents/CollegePitchSearch.jsx
src/views/OperationsModule/OperationComponents/Mentorship/MentorshipSearchbar.jsx
src/views/OperationsModule/OperationComponents/OpsSearchBar.js
src/views/OperationsModule/OperationComponents/TotSearchBar.jsx
src/views/OperationsModule/OperationComponents/UpskillSearchBar.jsx
src/views/OperationsModule/OperationComponents/UserTot.jsx
src/views/OperationsModule/OperationComponents/UserTotRowdata.js

added changes for operation mosule multiple filter

---

src/views/OperationsModule/OperationComponents/CollegepitchesEdit.jsx

fix pitch date not comming issue

---

src/views/OperationsModule/UploadFiles/AlumniQuery/QueryUpload.jsx
src/views/OperationsModule/UploadFiles/AlumniQuery/checkQuery.jsx
src/views/OperationsModule/UploadFiles/MentorShip/MentorshipUpload.jsx

Added changes for alumni bulk upload

---

src/views/OperationsModule/OperationComponents/Mentorship/MentorshipdataField.jsx
src/views/OperationsModule/UploadFiles/TOT/TotUpload.jsx

added changes for sis-246

---

src/graphql/operations.js
src/views/OperationsModule/OperationComponents/OperationCreateform.jsx
src/views/OperationsModule/OperationComponents/RowsData.js
src/views/OperationsModule/OperationComponents/operationsActions.js

added organization dropdown

---

src/views/Students/Student.jsx
src/views/Students/StudentComponents/MedhaviMemberships.jsx

added changes membership data not found issue

---

src/graphql/opportunities.js
src/graphql/student.js
src/validations/Opportunity.js
src/validations/Student.js
src/views/Opportunities/OpportunityComponents/Details.jsx
src/views/Opportunities/OpportunityComponents/OpportunityForm.jsx
src/views/Students/StudentComponents/EmploymentConnection.jsx
src/views/Students/StudentComponents/EmploymentConnectionForm.jsx

fix sis-249 feature

---

src/validations/Opportunity.js
src/validations/Student.js
src/views/Opportunities/OpportunityComponents/OpportunityForm.jsx
src/views/Students/StudentComponents/EmploymentConnectionForm.jsx

Fixes edit not working in **Opportunities** and **Employment Connection** forms:

fix edit not working in both opportunities and employment connection

---

src/views/OperationsModule/OperationComponents/OpsSearchBar.js
src/views/OperationsModule/UploadFiles/TOT/TotUpload.jsx

added changes for tot upload file and multiple filter option

---

src/views/OperationsModule/OperationComponents/OpsSearchBar.js

added changes for the multiple filter

---

src/views/OperationsModule/UploadFiles/TOT/TotUpload.jsx

Added changes for tot data upload

---

src/views/OperationsModule/UploadFiles/TOT/TotUpload.jsx

added changes for tot upload file

---

src/views/OperationsModule/OperationComponents/OpsSearchBar.js

added changes for opssearchbar

---

src/views/OperationsModule/OperationComponents/OpsSearchBar.js

added changes for ops upload feature
